title: Soundleaks | 声漏
email: iseansay@gmail.com
description: 声漏是每月在一次的集会，在这里音乐家、工程师、艺术家、科学家、作曲家和硬件爱好者，探索声音的新可能。
baseurl: ""
url: "http://www.soundleaks.org" # the base hostname & protocol for your site
twitter_username: soundleaks
github_username:  soundleaks

markdown: kramdown

collections:
  events:
    output: true
    permalink: /event/:path/
