title: Soundleaks | 声漏
email: soundleakschina@gmail.com
description: 声漏是一场涉及声音与音乐的聚会我们希望更多对声音或音乐相关的文化理论、技术探讨、科学研究以及创作表演感兴趣的朋友加入到我们当中。 声漏将定期举办围绕声音或音乐相关项目的讲座与理论推广并且有相关类型的创作等活动体验。
baseurl: ""
url: "http://www.soundleaks.org"
twitter_username: soundleaks
github_username: soundleaks
markdown: kramdown
mailling_list_signup_link: http://eepurl.com/4XlPP
weibo_url: http://weibo.com/soundleaks
twitter_url: https://twitter.com/soundleaks
timezone: Asia/Shanghai
permalink: /post/:title

collections:
  events:
    output: true
    permalink: /event/:path/

assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

assets:
  js_compressor:  uglifier
  css_compressor: sass
